from rotk.components import UnitType, UnitCategory, TerrainType, TerrainAdaptability

"""单位类型配置"""
UNIT_CONFIGS = {
    UnitType.SHIELD_INFANTRY: {
        "name": "刀盾兵",
        "category": UnitCategory.INFANTRY,
        "health": 120,
        "attack": 15,
        "defense": 12,
        "base_speed": 4.5,
        "max_speed": 6.0,
        "attack_range": 1.0,
        "food_consumption": 0.6,
        "symbol": "D",
        "size": 24,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.GOOD,
            TerrainType.FOREST: TerrainAdaptability.AVERAGE,
            TerrainType.MOUNTAIN: TerrainAdaptability.POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.POOR,
            TerrainType.SWAMP: TerrainAdaptability.POOR,
        },
    },
    UnitType.SPEAR_INFANTRY: {
        "name": "长戟兵",
        "category": UnitCategory.INFANTRY,
        "health": 100,
        "attack": 18,
        "defense": 8,
        "base_speed": 4.0,
        "max_speed": 5.5,
        "attack_range": 1.5,
        "food_consumption": 0.6,
        "symbol": "J",
        "size": 24,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.GOOD,
            TerrainType.FOREST: TerrainAdaptability.POOR,
            TerrainType.MOUNTAIN: TerrainAdaptability.POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.VERY_POOR,
            TerrainType.SWAMP: TerrainAdaptability.VERY_POOR,
        },
    },
    UnitType.SCOUT_CAVALRY: {
        "name": "斥候骑兵",
        "category": UnitCategory.CAVALRY,
        "health": 90,
        "attack": 12,
        "defense": 6,
        "base_speed": 8.0,
        "max_speed": 12.0,
        "attack_range": 1.0,
        "food_consumption": 0.8,
        "symbol": "Z",
        "size": 22,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.EXCELLENT,
            TerrainType.FOREST: TerrainAdaptability.POOR,
            TerrainType.MOUNTAIN: TerrainAdaptability.VERY_POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.VERY_POOR,
            TerrainType.SWAMP: TerrainAdaptability.VERY_POOR,
        },
    },
    UnitType.MOUNTED_ARCHER: {
        "name": "骑射手",
        "category": UnitCategory.CAVALRY,
        "health": 80,
        "attack": 14,
        "defense": 5,
        "base_speed": 7.5,
        "max_speed": 11.0,
        "attack_range": 4.0,
        "food_consumption": 0.7,
        "ammo_consumption": 1.0,
        "symbol": "Q",
        "size": 22,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.EXCELLENT,
            TerrainType.FOREST: TerrainAdaptability.POOR,
            TerrainType.MOUNTAIN: TerrainAdaptability.VERY_POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.VERY_POOR,
            TerrainType.SWAMP: TerrainAdaptability.VERY_POOR,
        },
    },
    UnitType.ARCHER: {
        "name": "弓箭手",
        "category": UnitCategory.RANGED,
        "health": 80,
        "attack": 18,
        "defense": 5,
        "base_speed": 4.0,
        "max_speed": 5.0,
        "attack_range": 5.0,
        "food_consumption": 0.5,
        "ammo_consumption": 1.0,
        "symbol": "G",
        "size": 20,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.GOOD,
            TerrainType.FOREST: TerrainAdaptability.AVERAGE,
            TerrainType.MOUNTAIN: TerrainAdaptability.POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.POOR,
            TerrainType.SWAMP: TerrainAdaptability.POOR,
        },
    },
    UnitType.CROSSBOWMAN: {
        "name": "弩手",
        "category": UnitCategory.RANGED,
        "health": 75,
        "attack": 22,
        "defense": 4,
        "base_speed": 3.5,
        "max_speed": 4.5,
        "attack_range": 4.0,
        "food_consumption": 0.5,
        "ammo_consumption": 0.8,
        "symbol": "N",
        "size": 20,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.GOOD,
            TerrainType.FOREST: TerrainAdaptability.POOR,
            TerrainType.MOUNTAIN: TerrainAdaptability.POOR,
            TerrainType.HILL: TerrainAdaptability.POOR,
            TerrainType.RIVER: TerrainAdaptability.POOR,
            TerrainType.SWAMP: TerrainAdaptability.POOR,
        },
    },
    UnitType.HEAVY_CAVALRY: {
        "name": "虎豹骑",
        "category": UnitCategory.CAVALRY,
        "health": 150,
        "attack": 25,
        "defense": 15,
        "base_speed": 6.0,
        "max_speed": 9.0,
        "attack_range": 1.0,
        "food_consumption": 1.0,
        "symbol": "H",
        "size": 26,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.EXCELLENT,
            TerrainType.FOREST: TerrainAdaptability.POOR,
            TerrainType.MOUNTAIN: TerrainAdaptability.VERY_POOR,
            TerrainType.HILL: TerrainAdaptability.AVERAGE,
            TerrainType.RIVER: TerrainAdaptability.VERY_POOR,
            TerrainType.SWAMP: TerrainAdaptability.VERY_POOR,
        },
    },
    UnitType.MOUNTAIN_INFANTRY: {
        "name": "无当飞军",
        "category": UnitCategory.INFANTRY,
        "health": 110,
        "attack": 16,
        "defense": 10,
        "base_speed": 5.0,
        "max_speed": 7.0,
        "attack_range": 1.0,
        "food_consumption": 0.5,
        "symbol": "F",
        "size": 24,
        "terrain_adaptability": {
            TerrainType.PLAINS: TerrainAdaptability.GOOD,
            TerrainType.FOREST: TerrainAdaptability.GOOD,
            TerrainType.MOUNTAIN: TerrainAdaptability.EXCELLENT,
            TerrainType.HILL: TerrainAdaptability.EXCELLENT,
            TerrainType.RIVER: TerrainAdaptability.AVERAGE,
            TerrainType.SWAMP: TerrainAdaptability.POOR,
        },
    },
}
