# this is a TOML file for key format
# change the values of the keys to your own values
# and adjust the file name to key.toml or what you want
[proxy] 
url= ""

[openai]
organization = ""
project = ""
api_key = ""

[anthropic]
api_key = ""

[bedrock]
service_name = ""
region_name = ""
aws_access_key_id = ""
aws_secret_access_key = ""

